server:
  port: 8765
  
eureka:
  client:
    service-url:
     defaultZone: http://localhost:8761/eureka 
      
      
spring:
  application:
    name: api-gateway
  cloud:
   gateway:
     discovery:
        locator:
          enabled: true
          #lower-case-service-id: true
     default-filters:
      - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
     globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "http://*"
              allowedMethods: 
              - POST
              - GET
              - DELETE
              - PUT
              - OPTIONS
              allowedHeaders: "*"
              allowCredentials: true         
          
          
          
          
     routes:     
     - id: invest-application
       uri: lb://invest-app
       predicates: 
       - Path=//api/invest/**